function output = dic_2d_analysis(trial_target, data_path, dic_path)
% DIC_2D_ANALYSIS Perform 2D Digital Image Correlation analysis
%   This function performs the 2D DIC analysis for the given trials.
%
% Parameters:
%   trial_target: Target trials to analyze
%   data_path: Path to the data directory
%   dic_path: Path to save DIC results
%
% All other parameters are loaded from parameter files
    fprintf('Begin of %s\n', mfilename);
    % Flatten all combinations (trial_jj, stereopair_kk)
    pairs_trials = combvec( 1:num_pair, trial_target)';

    % parfor over the flattened set of combinations
    output = cell(size(pairs_trials, 1), 1);
    parfor i = 1:size(pairs_trials, 1)
        pair_id = pairs_trials(i, 1);
        trial_id = pairs_trials(i, 2);
        fprintf('Trial ID: %d, Pair ID: %d\n', trial_id, pair_id);
        %output{i} = {sprintf("Trial ID: %d, Pair ID: %d", trial_id, pair_id), 'success', true};
        [o1, o2, o3]  = stepD_2DDIC( ...
            'baseDataPath', data_path, ...
            'baseResultPath', dic_path, ...
            'subject', subject_id, ...
            'material', material, ...
            'trial', sprintf("%03d", trial_id), ...
            'stereopair', pair_id, ...
            'phase', phase_id, ...
            'showvisu', showvisu, ...
            'idxstart_set', idx_frame_start, ...
            'idxend_set', idx_frame_end, ...
            'reftrial_setmanual', sprintf("%03d", ref_trial_id), ...
            'jump', frame_jump, ...
            'automatic_process', automatic_process);
        output{i} = [o1, o2, o3];
    end
    fprintf('End of %s\n', mfilename);
end
