% STEP D, E, F: 2D-DIC, 3D Reconstruction, Deformation analysis

%% Subject and Trial Settings
subject_id = "S09"; % Subject identifier
phase_id = "loading";  % Phase identifier
material_id = 2; % Material identifier
nfcond_set = [5]; % Number of conditions
spddxlcond_set = [0.04, 0.08]; % Speed conditions

%% Calibration Settings
calib_folder_set = "2";
ref_trial_id = 5; % Reference trial number

%% Frame Settings
idx_frame_start = 1;
idx_frame_end = 150;
frame_jump = 1;

%% Visualization Settings
showvisu = 0; % Boolean for visualization
debug_mode = 0; % Debug mode flag

%% DIC Global Constants
DIC.TRUE_FPS = 50;
DIC.LIMIT_GRAYSCALE = struct(...
    'default', 100,...
    'early_subjects', 70,...
    'threshold', 8  ... % Subject numbers below this use early_subjects value
);

%% DIC Analysis Parameters
DIC.filtering = struct(...
    'enabled', true...
);

DIC.ncorr = struct(...
    'analysis_direction', 'regular',...
    'subset_radius', struct(...
        'tracking', 40,...
        'matching', 60 ...
    ),...
    'subset_spacing', 10,...
    'cutoff', struct(...
        'tracking', 1e-5,...
        'matching', 1e-5 ...
    ),...
    'solver', struct(...
        'max_iterations', 100,...
        'num_threads', 1 ...
    ),...
    'strain_analysis', struct(...
        'enabled', 1,...
        'propagation', 'seed',...
        'auto_ref_change', 1,...
        'step_ref_change', 10 ...
    ) ...
);
